# Generated by Django 4.0.6 on 2022-08-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='url_title', max_length=300, verbose_name='نام در url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='نام برند'),
        ),
    ]
