# Generated by Django 4.0.6 on 2022-08-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_productgallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='images',
            new_name='image',
        ),
    ]
