# Generated by Django 4.0.6 on 2022-08-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='parent',
        ),
    ]
