# Generated by Django 4.0.6 on 2022-08-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_remove_productcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
