# Generated by Django 4.0.6 on 2022-08-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='ادرس')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس')),
                ('email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('copy_right', models.TextField(max_length=200, verbose_name='متن کپی رایت')),
                ('site_logo', models.ImageField(upload_to='images/site-settings', verbose_name='لوگو سایت')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
        ),
    ]
