# Generated by Django 4.0.6 on 2022-08-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_alter_contactus_is_read_by_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='massage',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=300, verbose_name='نام و نام خانوادگی'),
        ),
    ]
