# Generated by Django 4.0.6 on 2022-08-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='متن مقاله'),
        ),
    ]
