# Generated by Django 4.0.6 on 2022-08-13 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 8, 13), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
