# Generated by Django 4.0.6 on 2022-08-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
    ]
